### ISSUE TITLE
Move Docs to Wiki

### ISSUE THREAD

**Issue by jennparker** [silexlabs/Silex#607]
We have issues in a variety of places that need to be moved to the wiki. Let's use this issue to consolidate and track all of the different docs that need to be moved to the wiki or within the wiki. Initially, this will be ugly and there will be some duplication with other issues because up until now we have been tracking these individually and in many different places. It will get better as we move forward. 

It would be a great help if you move even one of these docs (don't feel like you need to take on all of them). Once you've moved an issue, please add a comment to this issue so we can remove it from the list. If you find more docs that need to be moved, please add them here. 

Docs to Move:
- [x] Move [How to Host An Instance of Silex](https://github.com/silexlabs/Silex/blob/develop/readme.md) to its own wiki page and add a link to the new page in [Tutorials and Guides](https://github.com/silexlabs/Silex/wiki/Tutorials-and-Guides) 
- [x] Move [Silex and HTML](https://github.com/silexlabs/Silex/issues/199) to its own wiki page and add a link to the new page in [Tutorials and Guides](https://github.com/silexlabs/Silex/wiki/Tutorials-and-Guides)
- [x] Move [Silex CSS editor](https://github.com/silexlabs/Silex/issues/184) to its own wiki page and add a link to the new page in [Tutorials and Guides](https://github.com/silexlabs/Silex/wiki/Tutorials-and-Guides)
- [x] Move [Silex and Javascript](https://github.com/silexlabs/Silex/issues/200) to its own wiki page and add a link to the new page in [Tutorials and Guides](https://github.com/silexlabs/Silex/wiki/Tutorials-and-Guides)
- [ ] Move [Silex publication process](https://github.com/silexlabs/Silex/issues/238) to its own wiki page and add a link to the new page in [Tutorials and Guides](https://github.com/silexlabs/Silex/wiki/Tutorials-and-Guides)
- [ ] Move [widget docs](https://github.com/silexlabs/Silex/issues/605) to [Editor IU](https://github.com/silexlabs/Silex/wiki/Editor-UI/_edit#widgets)
- [ ] Move [Contact Form Component](https://github.com/silexlabs/Silex/wiki/Contact-form-component) to [Editor Ui](https://github.com/silexlabs/Silex/wiki/Editor-UI/_edit#components).
- [x] Move [Live Map Component](https://github.com/silexlabs/Silex/wiki/Live-map-component) to [Editor Ui](https://github.com/silexlabs/Silex/wiki/Editor-UI/_edit#components).
- [x] Move [Share Bar Component](https://github.com/silexlabs/Silex/wiki/Share-bar-component) to [Editor Ui](https://github.com/silexlabs/Silex/wiki/Editor-UI/_edit#components).
- [x] Move [Skill Bar Component](https://github.com/silexlabs/Silex/wiki/Skill-bar-component
) to [Editor Ui](https://github.com/silexlabs/Silex/wiki/Editor-UI/_edit#components).
- [x] Move [Slideshow Component](https://github.com/silexlabs/Silex/wiki/Slideshow-component) to [Editor Ui](https://github.com/silexlabs/Silex/wiki/Editor-UI/_edit#components).
- [ ] Move [this issue](https://github.com/silexlabs/Silex/issues/282) to [FAQ](https://github.com/silexlabs/Silex/wiki/FAQ)

**Comment by stache1draht** [comment]
Moved Slideshow Component to Editor Ui.

**Comment by singchan** [comment]
thank you
I moved the "components" section below the "elements" section

**Comment by stache1draht** [comment]
Moved Skill Bar Component to Editor Ui. Put a link to the new page in [the original page](https://github.com/silexlabs/Silex/wiki/Skill-bar-component) similar to the changes made by singchan. As for the other sections where this component is mentioned, I do not know how to find them, so I did not substitute the links there. If anybody could provide instructions that would be great.

**Comment by stache1draht** [comment]
Moved Contact Form Component, Live Map Component, and Share Bar Component to Editor UI page. Updated the Editor UI page and removed the corresponding "Help needed" entry.

**Comment by stache1draht** [comment]
Moved [How to Host An Instance of Silex](https://github.com/silexlabs/Silex/blob/develop/readme.md) to its own [wiki page](https://github.com/silexlabs/Silex/wiki/How-to-Host-An-Instance-of-Silex). Updated the link in [Tutorials and Guides](https://github.com/silexlabs/Silex/wiki/Tutorials-and-Guides)

**Comment by lexoyo** [comment]
thank you @stache1draht !!

**Comment by stache1draht** [comment]
As for the other items in the list (those to be moved to Tutorials and Guides and Widget documents), I think, it would be reasonable if they are moved by their authors, since the authors can just copypaste texts of the posts to the new pages while other users will have to do extra work copying and formatting them all over. Meanwhile I can create blank pages for these items on the weekend. What do you think, guys?

**Comment by lexoyo** [comment]
Yes that's a good idea!

**Comment by stache1draht** [comment]
Created three blank pages:

https://github.com/silexlabs/Silex/wiki/Silex-and-HTML
https://github.com/silexlabs/Silex/wiki/Silex-CSS-editor
https://github.com/silexlabs/Silex/wiki/Silex-and-Javascript

[Silex publication process](https://github.com/silexlabs/Silex/issues/238) seems to have been moved already: https://github.com/silexlabs/Silex/wiki/Publishing-and-Releasing-Your-Website

So does [Contact form component](https://github.com/silexlabs/Silex/wiki/Editor-UI#contact-form-component).

**Comment by lexoyo** [comment]
@stache1draht I see the blank pages like https://github.com/silexlabs/Silex/wiki/Silex-CSS-editor
Could you move the issues like https://github.com/silexlabs/Silex/issues/184 to it?

**Comment by stache1draht** [comment]
@lexoyo, yes, I will get down to it as soon as I can. I have already started the work, moving https://github.com/silexlabs/Silex/wiki/Silex-and-HTML to its corresponding page, but I am on a pretty tight schedule right now. And it seems this article needs to be updated.

**Comment by lexoyo** [comment]
> Move Silex and Javascript to its own wiki page and add a link to the new page in Tutorials and Guides

done

**Comment by lexoyo** [comment]
> Move Silex and HTML to its own wiki page and add a link to the new page in Tutorials and Guides

it looks like @stache1draht did it already

**Comment by stache1draht** [comment]
I have just started the work. The task is not finished yet. I have copied approximately half of the text.

**Comment by lexoyo** [comment]
Oh no :(
I deleted the original issue and replaced it with a link to your wiki page...
Facepalm!

**Comment by stache1draht** [comment]
Is it possible to restore it somehow?

**Comment by lexoyo** [comment]
Not on github :(
Maybe with Google cache or something?

**Comment by stache1draht** [comment]
Nothing in Google Cache. I think, it's have to be rewritten.

**Comment by stache1draht** [comment]
Today I am going to start moving [this issue](https://github.com/silexlabs/Silex/issues/184) to [this page](https://github.com/silexlabs/Silex/wiki/Silex-CSS-editor). Please do not delete the original issue until I say I'm done.

**Comment by stache1draht** [comment]
We can return to Silex and HTML page after we are finished with moving other pages.

**Comment by lexoyo** [comment]
Ok

**Comment by stache1draht** [comment]
I have finished moving Silex CSS editor issue to the new Wiki-page.

**Comment by lexoyo** [comment]
Nice! 
🥇 
I have removed the content and put a link to the new page 

In the new wiki page I have added components css classes and sections which were missing. The screenshots are old and it would be great to have some actual examples... But it is a good start :)

Thx @stache1draht !!

**Comment by lexoyo** [comment]
Thank you for taking the time to open this issue.

We're closing older issues as part of a tracker cleanup to help the project focus on Silex v3. If this is still relevant to the current version, please feel free to open a new issue with updated details — we'd be happy to look into it.

You can try v3 at https://v3.silex.me and join the community at https://community.silex.me.
