### ISSUE TITLE
feature request: from widgets to components

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#703]
Most of the [widgets here](https://github.com/silexlabs/Silex/issues?q=is%3Aopen+is%3Aissue+label%3Awidget) could become components and appear in the "+" menu

These widgets could be easily ported 
* [ ] [Vertical Column Widget widget](#686)
* [ ] [Multi-columns section widget](#603)
* [ ] [Active menu for 1 page websites widget](#417)
* [ ] [Video Player Widget](#343)
* [ ] [Add sound to my website](#289)
* [ ] [Drop down menu for Silex](#247)
* [ ] [Accordion widget for Silex](#208)
* [ ] [Google + widget](#65) 
* [ ] [Facebook widget](#64) 
* [ ] [Twitter widget ](#63)

There are also widgets like the "hero section" which are already in silex but not activated, and [the low level components discussed in this issue](#277)
